//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataLayer
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class CoreItem
    {
        public int ItemId { get; set; }

        [Required(ErrorMessage ="Item Number required.")]
        public string ItemNumber { get; set; }
        [Required(ErrorMessage = "Vendor Code required.")]
        public string VendorCode { get; set; }
        public string ItemDescription { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> DeliveryCharge { get; set; }
        public Nullable<decimal> CostPrice { get; set; }
        public string Grade { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
